version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - API_KEY=${API_KEY}
      - QDRANT_URL=${QDRANT_URL}
    restart: unless-stopped
