version: "3.9"

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/app/api
      - ./scheduler:/app/scheduler
      - ./logs:/app/logs
    env_file:
      - .env
    ports:
      - "8080:10000"  # Falls du FastAPI lokal testen willst
    container_name: trend_scheduler
    restart: unless-stopped
