[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd app && python railway.py"
healthcheckPath = "/railway-health"
healthcheckTimeout = 200
restartPolicyType = "ON_FAILURE"

[environments]
[environments.production]
numReplicas = 1 